/**
 * Sole checked-in source for non-authoritative browser copy.
 *
 * Static keys may label navigation, sections, formatting, and disclosure.
 * They must never decide or reinterpret Task, decision, verification, risk, or
 * command truth; those remain projected WebContentMessage values.
 */
import type { WebLocalizedCatalogEntry } from "./content-types.ts";

function staticEntry(
	surface: WebLocalizedCatalogEntry["surface"],
	en: string,
	zhCN: string,
	args: WebLocalizedCatalogEntry["args"] = [],
): WebLocalizedCatalogEntry {
	return {
		args,
		surface,
		values: { en, "zh-CN": zhCN },
	};
}

export const WEB_STATIC_CONTENT_REGISTRY = {
	"app.brand": staticEntry("shared", "Taskflow", "Taskflow"),
	"app.opening-workspace": staticEntry(
		"shared",
		"Opening your Taskflow workspace…",
		"正在打开你的 Taskflow 工作区…",
	),
	"app.connected": staticEntry("shared", "Connected", "已连接"),
	"app.skip-to-content": staticEntry(
		"shared",
		"Skip to main content",
		"跳到主要内容",
	),
	"nav.home": staticEntry("simple", "Home", "首页"),
	"nav.tasks": staticEntry("simple", "Tasks", "任务"),
	"nav.needs-input": staticEntry("simple", "Needs your input", "需要你处理"),
	"nav.workspaces": staticEntry("simple", "Workspaces", "工作区"),
	"nav.settings": staticEntry("shared", "Settings", "设置"),
	"nav.pro.overview": staticEntry("pro", "Overview", "总览"),
	"nav.pro.timeline": staticEntry("pro", "Timeline", "时间线"),
	"nav.pro.graph": staticEntry("pro", "Graph", "关系图"),
	"nav.pro.evidence": staticEntry("pro", "Evidence", "证据"),
	"nav.pro.policy": staticEntry("pro", "Policy", "策略"),
	"nav.pro.diagnostics": staticEntry("pro", "Diagnostics", "诊断"),
	"nav.pro.replay": staticEntry("pro", "Replay", "重放"),
	"nav.pro.technical": staticEntry("pro", "Technical", "技术"),
	"nav.primary-label": staticEntry("shared", "Primary", "主导航"),
	"nav.open-navigation": staticEntry(
		"shared",
		"Open navigation",
		"打开导航",
	),
	"mode.simple.label": staticEntry("shared", "Simple", "简洁"),
	"mode.simple.description": staticEntry(
		"shared",
		"Focus on what happened and what to do next.",
		"只关注发生了什么，以及下一步该做什么。",
	),
	"mode.pro.label": staticEntry("shared", "Pro", "专业"),
	"mode.pro.description": staticEntry(
		"shared",
		"Show execution details, evidence, and diagnostics.",
		"显示执行细节、证据和诊断信息。",
	),
	"section.active-tasks": staticEntry("simple", "Active tasks", "正在进行"),
	"section.recent-tasks": staticEntry("simple", "Recent tasks", "最近任务"),
	"section.task-details": staticEntry("shared", "Task details", "任务详情"),
	"section.steps": staticEntry("shared", "Steps", "步骤"),
	"section.result": staticEntry("shared", "Result", "结果"),
	"section.verification": staticEntry("shared", "Verification", "结果验证"),
	"section.required-input": staticEntry(
		"simple",
		"Your decision",
		"需要你的决定",
	),
	"section.workspace": staticEntry("simple", "Workspace", "工作区"),
	"section.preferences": staticEntry("shared", "Preferences", "偏好设置"),
	"section.session": staticEntry("shared", "Current session", "当前会话"),
	"section.about": staticEntry("shared", "About Taskflow", "关于 Taskflow"),
	"section.pro.timeline": staticEntry("pro", "Execution timeline", "执行时间线"),
	"section.pro.graph": staticEntry("pro", "Task graph", "任务关系图"),
	"section.pro.node": staticEntry("pro", "Step inspector", "步骤检查器"),
	"section.pro.evidence": staticEntry("pro", "Evidence and checks", "证据与检查"),
	"section.pro.artifacts": staticEntry("pro", "Artifacts", "产物"),
	"section.pro.fragments": staticEntry("pro", "Dynamic fragments", "动态片段"),
	"section.pro.technical": staticEntry("pro", "Technical details", "技术详情"),
	"section.pro.why-stale": staticEntry("pro", "Reuse analysis", "复用分析"),
	"section.pro.source": staticEntry("pro", "Source details", "来源详情"),
	"section.pro.overview": staticEntry(
		"pro",
		"Control plane overview",
		"控制面总览",
	),
	"section.pro.replay": staticEntry("pro", "Zero-token replay", "零令牌重放"),
	"action.open-task": staticEntry("simple", "Open task", "打开任务"),
	"action.open-settings": staticEntry("shared", "Open settings", "打开设置"),
	"action.back": staticEntry("shared", "Back", "返回"),
	"action.close": staticEntry("shared", "Close", "关闭"),
	"action.refresh-view": staticEntry("shared", "Refresh view", "刷新页面"),
	"action.load-more": staticEntry("shared", "Load more", "加载更多"),
	"action.copy": staticEntry("shared", "Copy", "复制"),
	"action.copied": staticEntry("shared", "Copied", "已复制"),
	"action.show-details": staticEntry("shared", "Show details", "显示详情"),
	"action.hide-details": staticEntry("shared", "Hide details", "收起详情"),
	"action.show-pro": staticEntry("shared", "Switch to Pro", "切换到专业模式"),
	"action.show-simple": staticEntry(
		"shared",
		"Switch to Simple",
		"切换到简洁模式",
	),
	"action.stop-task": staticEntry("simple", "Stop task", "停止任务"),
	"action.download-artifact": staticEntry(
		"pro",
		"Download artifact {artifactId}",
		"下载产物 {artifactId}",
		[{ name: "artifactId", kind: "string" }],
	),
	"action.download-receipt-json": staticEntry(
		"pro",
		"Download Receipt JSON",
		"下载 Receipt JSON",
	),
	"action.run-replay": staticEntry("pro", "Run offline replay", "运行离线重放"),
	"action.check-command": staticEntry("shared", "Check outcome", "检查结果"),
	"action.retry-same-command": staticEntry(
		"shared",
		"Retry the same request",
		"重试同一请求",
	),
	"action.end-session": staticEntry("shared", "End this session", "结束当前会话"),
	"action.end-all-sessions": staticEntry(
		"shared",
		"End all sessions",
		"结束所有会话",
	),
	"action.keep-session": staticEntry("shared", "Keep session", "保留会话"),
	"settings.mode.label": staticEntry("shared", "Display mode", "显示模式"),
	"settings.theme.label": staticEntry("shared", "Appearance", "外观"),
	"settings.theme.system": staticEntry("shared", "Use system setting", "跟随系统"),
	"settings.theme.light": staticEntry("shared", "Light", "浅色"),
	"settings.theme.dark": staticEntry("shared", "Dark", "深色"),
	"settings.language.label": staticEntry("shared", "Language", "语言"),
	"settings.language.en": staticEntry("shared", "English", "英文"),
	"settings.language.zh-cn": staticEntry(
		"shared",
		"Simplified Chinese",
		"简体中文",
	),
	"settings.session-expires": staticEntry(
		"shared",
		"Session ends {expiresAt, datetime}",
		"会话将于 {expiresAt, datetime}结束",
		[{ name: "expiresAt", kind: "timestamp" }],
	),
	"settings.session.description": staticEntry(
		"shared",
		"End browser access without changing any task.",
		"结束浏览器访问，不会更改任何任务。",
	),
	"settings.session.end-question": staticEntry(
		"shared",
		"End this browser session?",
		"结束当前浏览器会话？",
	),
	"settings.session.end-impact": staticEntry(
		"shared",
		"This tab will lose access. Tasks will keep their current state.",
		"当前标签页将失去访问权限，任务会保持现有状态。",
	),
	"settings.session.end-all-question": staticEntry(
		"shared",
		"End every browser session?",
		"结束所有浏览器会话？",
	),
	"settings.session.end-all-impact": staticEntry(
		"shared",
		"Every open Taskflow tab for this listener will lose access. Tasks will keep their current state.",
		"这个监听器下所有已打开的 Taskflow 标签页都会失去访问权限，任务会保持现有状态。",
	),
	"summary.task-count": {
		args: [{ name: "count", kind: "count" }],
		surface: "simple",
		values: {
			en: {
				kind: "plural",
				arg: "count",
				one: "{count, number} task",
				other: "{count, number} tasks",
			},
			"zh-CN": "{count, number} 个任务",
		},
	},
	"summary.workspace-count": {
		args: [{ name: "count", kind: "count" }],
		surface: "simple",
		values: {
			en: {
				kind: "plural",
				arg: "count",
				one: "{count, number} workspace",
				other: "{count, number} workspaces",
			},
			"zh-CN": "{count, number} 个工作区",
		},
	},
	"summary.last-updated": staticEntry(
		"shared",
		"Updated {updatedAt, datetime}",
		"更新于 {updatedAt, datetime}",
		[{ name: "updatedAt", kind: "timestamp" }],
	),
	"summary.home-activity": staticEntry(
		"simple",
		"{activeCount, number} active · {inputCount, number} need you",
		"{activeCount, number} 个正在进行 · {inputCount, number} 个需要你处理",
		[
			{ name: "activeCount", kind: "count" },
			{ name: "inputCount", kind: "count" },
		],
	),
	"description.home": staticEntry(
		"simple",
		"A calm view of what is happening now and what needs your attention.",
		"清楚了解当前正在发生什么，以及哪些事情需要你处理。",
	),
	"description.tasks": staticEntry(
		"simple",
		"Every task keeps its workspace identity and latest authoritative state.",
		"每个任务都保留所属工作区及最新的权威状态。",
	),
	"description.needs-input": staticEntry(
		"simple",
		"Decisions and uncertain work stay visible until the authoritative source is clear.",
		"需要决定或尚不确定的工作会持续显示，直到权威状态明确。",
	),
	"description.workspaces": staticEntry(
		"simple",
		"Each workspace keeps its own authoritative task history.",
		"每个工作区都保留独立且权威的任务记录。",
	),
	"description.policy": staticEntry(
		"pro",
		"Read-only policy decisions from the current authority.",
		"查看当前权威来源给出的只读策略结论。",
	),
	"description.diagnostics": staticEntry(
		"pro",
		"Uncertain state and operator evidence without changing domain truth.",
		"查看不确定状态和操作证据，不改变权威事实。",
	),
	"description.workspace-ready": staticEntry(
		"simple",
		"This workspace is ready and its task history is authoritative.",
		"这个工作区已就绪，任务记录来自权威来源。",
	),
	"description.workspace-unverified": staticEntry(
		"simple",
		"Taskflow cannot verify this workspace right now.",
		"Taskflow 目前无法确认这个工作区的权威状态。",
	),
	"description.approval-status-only": staticEntry(
		"simple",
		"This request is visible, but no decision is currently available.",
		"你可以查看这项请求，但当前无法作出决定。",
	),
	"description.settings-language": staticEntry(
		"shared",
		"Content changes in this tab only.",
		"语言设置只在当前标签页生效。",
	),
	"description.settings-theme": staticEntry(
		"shared",
		"Appearance follows your system unless you choose otherwise.",
		"默认跟随系统外观，也可以在这里单独选择。",
	),
	"workspace.history-ready": staticEntry(
		"simple",
		"Task history is available.",
		"任务记录可用。",
	),
	"approval.review-impact": staticEntry(
		"simple",
		"Review the request and its impact.",
		"查看这项请求及其影响。",
	),
	"approval.decision-due": staticEntry(
		"simple",
		"Decision due {dueAt, datetime}",
		"请在 {dueAt, datetime}前作出决定",
		[{ name: "dueAt", kind: "timestamp" }],
	),
	"error.fallback-headline": staticEntry(
		"shared",
		"Taskflow could not load this view.",
		"Taskflow 无法加载这个页面。",
	),
	"error.fallback-detail": staticEntry(
		"shared",
		"The current information was not changed.",
		"当前信息没有被更改。",
	),
	"error.fallback-next": staticEntry(
		"shared",
		"Refresh the view to try again.",
		"刷新页面后重试。",
	),
	"command.checking.headline": staticEntry(
		"shared",
		"Checking whether the action was saved",
		"正在确认操作是否已保存",
	),
	"command.checking.detail": staticEntry(
		"shared",
		"Taskflow will not submit it again until the saved outcome is known.",
		"确认已保存的结果前，Taskflow 不会重复提交。",
	),
	"command.recorded.headline": staticEntry(
		"shared",
		"The action was saved and is still being applied",
		"操作已保存，仍在处理中",
	),
	"command.recorded.detail": staticEntry(
		"shared",
		"Check again for its latest authoritative outcome.",
		"再次检查以获取最新的权威结果。",
	),
	"command.unknown.headline": staticEntry(
		"shared",
		"Taskflow cannot confirm the action yet",
		"Taskflow 暂时无法确认这次操作",
	),
	"command.unknown.detail-retry": staticEntry(
		"shared",
		"The original request is still available in this tab. Check again, or retry that exact request without creating a second action.",
		"当前标签页仍保留原始请求。你可以再次检查，或重试完全相同的请求；这不会创建第二次操作。",
	),
	"command.unknown.detail-refresh": staticEntry(
		"shared",
		"The original request is no longer available in this tab. Check again, then refresh the current task before deciding whether to submit a new action.",
		"当前标签页已不再保留原始请求。请先再次检查，再刷新当前任务，然后决定是否提交新的操作。",
	),
	"pro.metric.capacity": staticEntry("pro", "Capacity", "容量"),
	"pro.metric.healthy-workspaces": staticEntry(
		"pro",
		"Healthy workspaces",
		"健康工作区",
	),
	"pro.metric.reused-nodes": staticEntry("pro", "Reused nodes", "复用节点"),
	"pro.field.code": staticEntry("pro", "Code", "代码"),
	"pro.field.message": staticEntry("pro", "Message", "消息"),
	"pro.field.cache": staticEntry("pro", "Cache explanation", "缓存说明"),
	"pro.field.definition": staticEntry("pro", "Definition", "定义"),
	"pro.field.project": staticEntry("pro", "Project", "项目"),
	"pro.field.domain": staticEntry("pro", "Domain", "控制域"),
	"pro.field.binding": staticEntry("pro", "Binding", "绑定"),
	"pro.field.approval-version": staticEntry(
		"pro",
		"Approval version",
		"审批版本",
	),
	"pro.field.race-state": staticEntry("pro", "Race state", "竞争状态"),
	"pro.field.dispatcher-handoff": staticEntry(
		"pro",
		"Dispatcher handoff",
		"调度器交接",
	),
	"pro.field.bound-plan": staticEntry("pro", "Bound plan", "BoundPlan"),
	"pro.field.version": staticEntry("pro", "Version", "版本"),
	"pro.field.browser-protocol": staticEntry(
		"pro",
		"Browser protocol",
		"浏览器协议",
	),
	"pro.field.session": staticEntry("pro", "Session", "会话"),
	"pro.field.run": staticEntry("pro", "Run", "运行"),
	"pro.field.run-version": staticEntry("pro", "Run version", "运行版本"),
	"pro.field.event-manifest": staticEntry("pro", "Event manifest", "事件清单"),
	"pro.field.journal-continuity": staticEntry(
		"pro",
		"Journal continuity",
		"日志连续性",
	),
	"pro.field.provenance": staticEntry("pro", "Provenance", "来源"),
	"pro.field.artifact-integrity": staticEntry(
		"pro",
		"Artifact integrity",
		"产物完整性",
	),
	"pro.field.provider-consistency": staticEntry(
		"pro",
		"Provider consistency",
		"执行来源一致性",
	),
	"pro.field.receipt": staticEntry("pro", "Receipt", "Receipt"),
	"pro.field.provider-calls": staticEntry("pro", "Provider calls", "执行服务调用"),
	"pro.field.durable-writes": staticEntry("pro", "Durable writes", "持久写入"),
	"pro.value.not-recorded": staticEntry("pro", "Not recorded", "未记录"),
	"pro.timeline.commit": staticEntry(
		"pro",
		"Commit {commitSeq, number}",
		"提交序号 {commitSeq, number}",
		[{ name: "commitSeq", kind: "count" }],
	),
	"pro.graph.read-only-label": staticEntry(
		"pro",
		"Read-only task graph",
		"只读任务关系图",
	),
	"pro.graph.accessible-list": staticEntry(
		"pro",
		"Open accessible graph list",
		"打开无障碍关系列表",
	),
	"pro.graph.node-count": staticEntry(
		"pro",
		"{count, number} nodes",
		"{count, number} 个节点",
		[{ name: "count", kind: "count" }],
	),
	"pro.graph.depends-on": staticEntry("pro", "Depends on", "依赖"),
	"pro.graph.no-dependencies": staticEntry(
		"pro",
		"No dependencies",
		"没有依赖项",
	),
	"pro.graph.open-step": staticEntry(
		"pro",
		"Inspect {phaseId}",
		"检查 {phaseId}",
		[{ name: "phaseId", kind: "string" }],
	),
	"pro.graph.zoom-in": staticEntry("pro", "Zoom in", "放大"),
	"pro.graph.zoom-out": staticEntry("pro", "Zoom out", "缩小"),
	"pro.graph.reset-view": staticEntry("pro", "Reset graph view", "重置关系图"),
	"pro.evidence.event-manifest": staticEntry(
		"pro",
		"Event manifest",
		"事件清单",
	),
	"pro.evidence.journal-continuity": staticEntry(
		"pro",
		"Journal continuity",
		"日志连续性",
	),
	"pro.evidence.provenance": staticEntry("pro", "Provenance", "来源"),
	"pro.evidence.artifact-integrity": staticEntry(
		"pro",
		"Artifact integrity",
		"产物完整性",
	),
	"pro.evidence.provider-consistency": staticEntry(
		"pro",
		"Provider consistency",
		"执行来源一致性",
	),
	"pro.replay-zero-write": staticEntry(
		"pro",
		"Replay never calls a provider or writes durable state.",
		"重放不会调用执行服务，也不会写入持久状态。",
	),
	"pro.replay.available": staticEntry(
		"pro",
		"This task has a replayable trace.",
		"这个任务包含可重放的跟踪记录。",
	),
	"pro.replay.unavailable": staticEntry(
		"pro",
		"This task cannot be fully replayed offline.",
		"这个任务无法完全离线重放。",
	),
	"pro.replay.result": staticEntry("pro", "Replay result", "重放结果"),
	"progress.exact": staticEntry(
		"simple",
		"{completed, number} of {total, number} steps completed",
		"已完成 {completed, number}/{total, number} 个步骤",
		[
			{ name: "completed", kind: "count" },
			{ name: "total", kind: "count" },
		],
	),
	"progress.lower-bound": staticEntry(
		"simple",
		"At least {completed, number} steps completed",
		"至少已完成 {completed, number} 个步骤",
		[{ name: "completed", kind: "count" }],
	),
	"progress.indeterminate": staticEntry(
		"simple",
		"Progress is not available yet",
		"暂时无法显示进度",
	),
	"step-state.pending": staticEntry("simple", "Pending", "等待开始"),
	"step-state.running": staticEntry("simple", "In progress", "正在进行"),
	"step-state.waiting": staticEntry("simple", "Waiting", "正在等待"),
	"step-state.completed": staticEntry("simple", "Completed", "已完成"),
	"step-state.failed": staticEntry("simple", "Failed", "未完成"),
	"step-state.cancelled": staticEntry("simple", "Stopped", "已停止"),
	"step-state.blocked": staticEntry("simple", "Blocked", "已阻塞"),
	"graph.legend.depends-on": staticEntry("pro", "Depends on", "依赖"),
	"graph.legend.control": staticEntry("pro", "Control flow", "控制流"),
	"graph.selected-step": staticEntry("pro", "Selected step", "已选步骤"),
	"evidence.current-checks": staticEntry("pro", "Current checks", "当前检查"),
	"evidence.immutable-record": staticEntry(
		"pro",
		"Immutable Receipt",
		"不可变 Receipt",
	),
	"evidence.first-page": staticEntry(
		"pro",
		"Showing the first {count, number} records",
		"显示前 {count, number} 条记录",
		[{ name: "count", kind: "count" }],
	),
	"evidence.export-check-title": staticEntry(
		"pro",
		"Local export check",
		"本地导出检查",
	),
	"evidence.export-check-detail": staticEntry(
		"pro",
		"Before download, Taskflow checks that every event named by this Receipt is present once and in order. This checks the exported file only; the evidence status above remains authoritative.",
		"下载前，Taskflow 会检查这份 Receipt 指定的每个事件是否都完整、唯一并按顺序写入。此检查只验证导出文件的一致性；上方的证据状态仍是权威结论。",
	),
	"evidence.export-downloaded": staticEntry(
		"pro",
		"Receipt JSON downloaded. Its event list matched this Receipt.",
		"Receipt JSON 已下载，其中的事件列表与这份 Receipt 一致。",
	),
	"evidence.export-failed": staticEntry(
		"pro",
		"The Receipt JSON was not downloaded because its event list could not be confirmed. Refresh this task and try again.",
		"由于无法确认事件列表，Receipt JSON 未下载。请刷新任务后重试。",
	),
	"pro.source.control-store": staticEntry("pro", "ControlStore", "ControlStore"),
	"pro.field.run-status": staticEntry("pro", "RunStatus", "RunStatus"),
	"pro.field.run-stage": staticEntry("pro", "RunStage", "RunStage"),
	"pro.field.commit-seq": staticEntry("pro", "commitSeq", "commitSeq"),
	"pro.field.watermark": staticEntry("pro", "watermark", "watermark"),
	"pro.field.provider": staticEntry("pro", "provider", "provider"),
	"pro.field.request-id": staticEntry("pro", "Request ID", "请求 ID"),
	"pro.field.command-id": staticEntry("pro", "Command ID", "命令 ID"),
	"pro.field.schema-version": staticEntry("pro", "Schema version", "Schema 版本"),
} as const satisfies Record<string, WebLocalizedCatalogEntry>;

export type WebStaticContentKey = keyof typeof WEB_STATIC_CONTENT_REGISTRY;
export const WEB_STATIC_CONTENT_KEYS = Object.freeze(
	Object.keys(WEB_STATIC_CONTENT_REGISTRY).sort((a, b) =>
		a.localeCompare(b, "en"),
	) as WebStaticContentKey[],
);
